---
title: "Useful_resources"
author: "Alexander Cormack"
date: "20 August 2022"
output: html_document
---



### Official instructions for RMySQL

https://biostat.app.vumc.org/wiki/Main/RMySQL



### Potentially useful guide for RMySQL

http://www.ahschulz.de/2013/07/23/installing-rmysql-under-windows/



### RMySQL vignette

https://cran.r-project.org/web/packages/RMySQL/RMySQL.pdf



### List of commands

https://www.pantz.org/software/mysql/mysqlcommands.html

* Do not, do not, delete, add or join things from esembl. Only select
* In general be careful with MySQL commands



### A nice blog summarising some other commands

https://www.r-bloggers.com/2011/08/mysql-and-r/



### HDF (hierarchical data format) storage structure

http://www.hdfgroup.org/



### Install bioconductor packages (biocLite.R for installing the R HDF5 package)

https://bioconductor.org/install/index.html#install-bioconductor-packages



### rhdf5 tutorial

https://www.bioconductor.org/packages/devel/bioc/vignettes/rhdf5/inst/doc/rhdf5.html


### Web scraping

https://en.wikipedia.org/wiki/Web_scraping

http://cran.r-project.org/web/packages/httr/httr.pdf

http://www/r-bloggers.com/?s=Web+Scraping


### Application programming interfaces

https://developer.twitter.com/en/docs/api-reference-index

https://developer.twitter.com/en/docs/tutorials/getting-started-with-r-and-v2-of-the-twitter-api


### Managing secrets

https://cran.r-project.org/web/packages/httr/vignettes/secrets.html


### Foreign package

http://cran.r-project.org/web/packages/foreign/foreign.pdf


### RPostgreSQL

* Tutorial http://code.google.com/p/rpostgresql/
* Help file http://cran.r-project.org/web/packages/RPostgreSQL/RPostgreSQL.pdf


### RODBC 

* Tutorial http://cran.r-project.org/web/packages/RODBC/vignettes/RODBC.pdf
* file http://cran.r-project.org/web/packages/RODBC/RODBC.pdf


### RMongo

* http://cran.r-project.org/web/packages/RMongo/RMongo.pdf
* example of RMongo http://www.r-bloggers.com/r-and-mongodb/


### Reading images

* jpeg http://cran.r-project.org/web/packages/jpeg/index.html
* readbitmap http://cran.r-project.org/web/packages/readbitmap/index.html
* png http://cran.r-project.org/web/packages/png/index.html
* EBImage (Bioconductor) http://www.bioconductor.org/packages/2.13/bioc/html/EBImage.html


### Reading GIS data

* rdgal http://cran.r-project.org/web/packages/rgdal/index.html
* rgeos http://cran.r-project.org/web/packages/rgeos/index.html
* raster http://cran.r-project.org/web/packages/raster/index.html


### Reading music data

* tuneR http://cran.r-project.org/web/packages/tuneR
* seewave http://rug.mnhn.fr/seewave/


### Subsetting and sorting

http://www.biostat.jhsph.edu/~ajaffe/lec_winterR/Lecture%202.pdf


### Creating new variables

http://www.biostat.jhsph.edu/~ajaffe/lec_winterR/Lecture%202.pdf
https://www.statmethods.net/management/functions.html
http://plyr.had.co.nz/09-user/


### Tidy data

http://vita.had.co.nz/papers/tidy-data.pdf

https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0026895


### Reshaping

http://www.r-bloggers.com/a-quick-primer-on-split-apply-combine-problems/

http://plyr.had.co.nz/09-user/

http://www.slideshare.net/jeffreybreen/reshaping-data-in-r


### Merging data

* the quick R data merging page: http://www.statmethods.net/management/merging.html

* plyr information: http://plyr.had.co.nz/

* types of joins: http://en.wikipedia.org/wiki/Join_(SQL)


### Dates and times

http://www.r-statistics.com/2012/03/do-more-with-dates-and-times-in-r-with-lubridate-1-1-0/

http://cran.r-project.org/web/packages/lubridate/vignettes/lubridate.html

Ultimately you want your dates and times as class "Date" or the classes "POSIXct", POSIXlt"
For more information type ?POSIXlt


### Data resources

Open Government Sites

- United Nations http://data.un.org/ 
- United States https://data.gov/
- United Kingdom https://www.data.gov.uk/
- France https://www.data.gouv.fr/fr/
- Australia https://www.data.gov.au/
- Germany https://www.govdata.de/
- HOng Kong https://data.gov.hk/en-data/dataset
- Japan https://www.data.go.jp/
- Many more https://data.gov/opendatasites/

Others

- Gapminder https://www.gapminder.org/
- Analyze Survey Data for Free http://asdfree.com/
- Kaggle https://www.kaggle.com/


From this blog

- https://medium.com/@gauravkumarindia/free-datasets-for-research-and-development-in-data-science-machine-learning-and-deep-learning-2b67580b73d4

- IEEE Data Port: https://ieee-dataport.org/
- UCI: https://archive.ics.uci.edu/ml/datasets.php
- Datahub http://datahub.io/
- Govt. of India http://data.gov.in/
- Book-Crossing http://www.informatik.unifreiburg.de/~cziegler/BX/
- World Health Organization http://www.who.int/research/en/
- The World Bank http://data.worldbank.org/
- NASA http://data.nasa.gov/
- United States Government http://www.data.gov/
- Machine Learning http://bitly.com/bundles/bigmlcom/2
- Scientific Data University of Muenster http://data.uni-muenster.de/
- Agriculture Datasets https://data.world/datasets/agriculture
- Assorted Domains https://knoema.com/atlas/India/topics/Agriculture/datasets






