---
title: "M3_W4_02_Regular_Expressions_II"
author: "Alexander Cormack"
date: "15 October 2022"
output: html_document
---

# Regular Expressions II

### More Metacharacters

"." is used to refer to any character, so:

- 9.11

will match these lines:

- its stupid the post 9-11 rules
- if any 1 of us did 9/11 we would have been caught in days.
- NetBios: scanning ip 203.169.114.66
- Front Door 9:11:45 AM
- Sings: 0118999881999119725...3 !


The | character does not mean "pipe" in the context of regular expressions; instead it translates to "or"; we can use it to combine two expressions, the subexpressions being called alternatives

-  flood|fire

will match these lines:

- is firewire like usb on none macs?
- the global flood makes sense within the context of the bible
- yeah ive had the fire on tonight
- ... and the floods, hurricanes, killer heatwaves, rednecks, gun nuts, etc.


We can include any number of alternatives:

flood|earthquake|hurricane|coldfire

will match these lines:

- Not a whole lot of hurricanes in the Arctic.
- We do have earthquakes newrly every day somewhere in our State
- hurricanes swirl in the other direction
- coldfire is STRAIGHT!
- 'cause we keep getting earthquakes


The alternatives can be regular expressions and not just literals:

- ^[Gg]ood|[Bb]ad

will match these lines:

- good to hear some good knews from someone here
- Good afternoon fellow american infidels!
- good on you-what do you drive?
- Katie... guess they had bad experiences...
- my middle name is trouble, Miss Bad News


Subexpressions are often contained in parentheses to constrain the alternatives:

- ^([Gg]ood|[Bb]ad)

will match these lines:

- bad habit
- bad coordination today
- good, because there is nothing worse than a man in kinky underwear
- Badcop, its because people want to use drugs
- Good Monday Holiday
- Good riddance to Limey


The question mark indicates that the indicated expression is optional:

- [Gg]eorge( [Ww\.)? [Bb]ush])

will match these lines:

- i bet i can spell better than you and george bush combined
- BBC reported that President George W. Bush claimed God told him to invade I
- a bird in the hand is worth two george bushes


The * and the + signs are metacharacters used to indicate repetition; * means "any number, including none, of the item"and + means "at least on of the item"

- (.*)

will match these lines:

- anyone wanna chat? (24, m, germany)
- hello, 20.m here... ( east area + drives + webcam )
- He means older men)
- ()


- [0-9]+ (.*)[0-9]+

will match these lines:

- working as MP here 720 MP battalions, 42nd brigade
- so say 2 or 3 years at college and 4 at uni makes us 23 when and if we fin
- it went down on several occasions for like, 3 or 4 *days*
- Mmm its time 4 me 2 go 2 bed


{ and } are referred to as interval quantifiers; they let us specify the minimum and maximum number of matches of an expression

- [Bb]ush( +[^ ]+ +){1,5} debate

will match these lines:

- Bush historically won all major debates he's done.
- in my view, Bush doesn't need these debates..
- bush doesn't need the debates? maybe you are right
- That's what Bush supporters are doing about the debate.
- Felix, I don't disagree that Bush was poorly prepared for the debate.
- indeed, but still, Bush should have taken the debate more seriously.
- Keep repeating that Bush smirked and scowled during the debate


{m,n} means at least me but not more than n matches
{m} means exactly m matches
{m,} means at leas m matches


In most implementations of regular expressions, the parentheses not only limit the scope of the alternatives divided by a "|", but also can be used to "remember" text matched by the subexpression enclosed

We refer to the matched text with \1, \2, etc.

So the expression:

-  +([a-zA-Z]+) +\1 +

will match these lines:

- time for bed, night night twitter!
- blah blah blah balh
- my tattoo is so so itchy today
- i was standing all all alone against the world outside...
- hi anybody anybody at home
- estudiando css css css css.... que desastritooooo


The * is "greedy" so it always matches the longest possible string that satsifies the regular expression. So:

- ^s(.*)s

will match these lines:

- sitting at starbucks
- setting up mysql and rails
- studying stuff for the exams
- spaghetti with marshmallows
- stop fighting with crackers
- sore shoulders, stupid ergonomics


The greediness of * can be turned off with the ?, as in:

- ^s(.*?)s$


### Summary

Regular expressions are used in many different languages: not unique to R.

Regular expressions are composed of literals and metacharacters that represent sets or classes of characters/words.

Text processing via regular expressions is a very powerful way to extract data from "unfriendly" sources (not all data comes as a CSV file)

Used with the functions grep, grepl, sub, gsub and other that involve searching for text strings.